### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by jainaayush01**
Fixed Typo

### CODE REVIEW

**Comment by vineelsai26** [comment]
Thank you didn't saw that ☺️☺️☺️

**Comment by jainaayush01** [comment]
No problem, btw I got to know it from the paint-project in which you are the mentor.
Have some doubts regarding it. Should I write it out here or mail it to you?

**Comment by vineelsai26** [comment]
Mail me vineelsai26@gmail.com

**Comment by jainaayush01** [comment]
Ok Thanks

**Pull request merged**
